# SPDX-FileCopyrightText: 2026-present Arthit Suriyawongkul
# SPDX-License-Identifier: Apache-2.0

name: Build wheels

on:
  push:
    branches: [ master ]
    paths:
      - "python/**/*.py"
      - "python/pyproject.toml"
      - "python/src/stopwordsiso/stopwords-iso.json"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "python/**/*.py"
      - "python/pyproject.toml"
      - "python/src/stopwordsiso/stopwords-iso.json"
      - ".github/workflows/build.yml"

jobs:
  build-wheel:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10", "3.14" ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          pip install --upgrade build pip
          pip install .

      - name: Build wheel
        id: build
        run: |
          python -m build
