# SPDX-FileCopyrightText: 2026-present Arthit Suriyawongkul
# SPDX-License-Identifier: Apache-2.0

name: Type checking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: python

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install mypy

      - name: Run mypy
        run: |
          mypy src/ --ignore-missing-imports --no-strict-optional
        continue-on-error: true
